server:
  port: ${PORT:${random.int(8000,8999)}}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CuotaDB
    username: postgres
    password: ezequiel2001
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

