server:
  port: 8080 # El puerto donde corre el servicio
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EstudianteDB
    username: postgres
    password: ezequiel2001
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
