server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: estudiante-service
          uri: lb://estudiante-service
          predicates:
            - Path=/Estudiante/**
        - id: cuota-service
          uri: lb://cuota-service
          predicates:
            - Path=/Cuota/**
        - id: examen-service
          uri: lb://examen-service
          predicates:
            - Path=/Examen/**
