server:
  port: 8081
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Hardezer/microsevices-data-project
          search-paths: config-data